### ISSUE TITLE
$:/config/DefaultSidebarTab not working

### ISSUE THREAD

**Issue by hegart-dmishiv** [danielo515/TW5-auto-publish2gh-pages#2]
In my cloned repo, I created a new folder called [/config](https://github.com/hegart-dmishiv/my-TW5-dev-instance/tree/master/wiki/tiddlers/system/config) under [/wiki/tiddlers/system](https://github.com/hegart-dmishiv/my-TW5-dev-instance/tree/master/wiki/tiddlers/system) and created there a tiddler called [DefaultSidebarTab.tid](https://github.com/hegart-dmishiv/my-TW5-dev-instance/blob/master/wiki/tiddlers/system/config/DefaultSidebarTab.tid) which I copied exactly from [the same file hosted on Google Drive](https://googledrive.com/host/0B7OVeQzNSpUGOFdLY2hIbWJNMHM/#%24%3A%2Fconfig%2FDefaultSidebarTab). This is supposed to set the focus on my custom [Contents](https://hegart-dmishiv.github.io/my-TW5-dev-instance/#Contents) tab in the SideBar whenever the wiki is loaded or refreshed in the web browser. It works fine in [Google Drive](https://googledrive.com/host/0B7OVeQzNSpUGOFdLY2hIbWJNMHM), but not here in [GitHub](https://hegart-dmishiv.github.io/my-TW5-dev-instance).

I've also raised this issue in the [discussion forums](https://groups.google.com/d/msg/tiddlywiki/s8pnvQW5UgY/Ow-vjgq3AwAJ).

**Comment by danielo515** [comment]
That is because you have a line feed at the end of the file. It is not evident when you are viewing the file, but if you edit it you can see that it has 5 lines, where it should only have 4. Remove the last line and you are ready to go. Github/git usually adds line feeds for you, and tiddlywiki does not like them on config tiddlers. I don't know what is worse, git doing things without asking or tiddlywiki being so picky.

Regards

**Comment by hegart-dmishiv** [comment]
It took a bit of doing. I tried twice to make the change in the GitHub web UI, but Git insisted on the extra linefeed. Then I signed up for a Prose.io account and did it there. The first time didn't take, and I still ended up with 5 lines of code, including the extra linefeed. The second time I did it through Prose it worked perfectly.

Thanks for the help on this. Oh, and please don't feel that you need to reply to me both here and in the discussion forums. I'll post my issues in both places, and if the TW community gets back to me faster than you do with a solution, I'll just post a link here to the answer and close the issue. I'll do the same _vice versa_ if you reply to me here sooner than the community responds. My issues, my responsibility. No need for extra effort on your part. ;-)

**Comment by danielo515** [comment]
> Thanks for the help on this. 

You're welcome. Is cool to see that people actually uses what you creates.

> Oh, and please don't feel that you need to reply to me both here and in the discussion forums. I'll post my issues in both places,

I do it because people usually search on the google group, so they are able to find the solution.

>if the TW community gets back to me faster than you do with a solution, I'll just post a link here to the answer and close the issue. I'll do the same vice versa if you reply to me here sooner than the community responds. My issues, my responsibility. No need for extra effort on your part. ;-)

OK! I'll rely on you that task.

Regards
