### ISSUE TITLE
Cannot edit $:/favicon.ico

### ISSUE THREAD

**Issue by hegart-dmishiv** [danielo515/TW5-auto-publish2gh-pages#3]
I have a custom favicon in my old online (**dev**) public wiki [hosted on Google Drive](https://googledrive.com/host/0B7OVeQzNSpUGOFdLY2hIbWJNMHM/#%24%3A%2Ffavicon.ico). I'm trying to migrate this to my new online public wiki [hosted on GitHub](https://hegart-dmishiv.github.io/my-TW5-dev-instance/#%24%3A%2Ffavicon.ico). What I see in the GitHub web UI is that the favicon file has been split in two. The [favicon.ico](https://github.com/hegart-dmishiv/my-TW5-dev-instance/blob/master/wiki/tiddlers/system/favicon.ico) file, which appears to be binary content, according to your commit [#a240676](https://github.com/danielo515/TW5-auto-publish2gh-pages/commit/a2406760300bc5e67af4b3bcaf1f89149fa2ae3e#diff-84a6555b32244a2c597c1e2d8db64657), is not editable in my cloned repo. The [favicon.ico.meta](https://github.com/hegart-dmishiv/my-TW5-dev-instance/blob/master/wiki/tiddlers/system/favicon.ico.meta) file only contains the basic tiddler info...

`title: $:/favicon.ico`
`type: image/x-icon`

...which is editable, but seems useless without the other part, which I assume is the base64-encoded binary data comprising the image itself. The resultant file [hosted on GitHub](https://hegart-dmishiv.github.io/my-TW5-dev-instance/#%24%3A%2Ffavicon.ico) is a single unified tiddler, as would normally be expected. I have no idea how to change my favicon now because of this.

I have also raised this issue in the [discussion forums](https://groups.google.com/d/msg/tiddlywiki/s8pnvQW5UgY/8ybf--q8AwAJ).

**Comment by danielo515** [comment]
As I said on the forum, I think  your best bet is to delete the favicon.ico file, and then create a new file replacing it. You can use http://prose.io/ to remove the file, and to create a new one. I think the best thing is to remove both, favicon.ico.meta and favicon.ico and put a tiddler containing the image in text form.

Let me know if you finally succeed.

**Comment by hegart-dmishiv** [comment]
Okay, done, thanks for that. Having not used Prose.io before, I was a little unsure of the interface, thinking the instructions at the bottom of the page for creating a new file were just part of the UI. Turns out they were default text, and I had saved that with my base64-encoded image. No wonder it didn't work for me at first! Hahaha.

The favicon is now working perfectly, thanks again.
